require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false

Lint/MissingSuper:
  AllowedParentClasses: [BaseCalculator]

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'lib/tasks/*'

Metrics/MethodLength:
  Max: 20

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/integration/shipments_spec.rb'
RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/shipments_spec.rb'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
