# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'db/seeds.rb'

Metrics/MethodLength:
  Max: 20

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
